apiVersion: v1
kind: Secret
metadata:
  name: github.com-acarter-ims
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/acarter-ims/ac-test
