apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argo-cd-ui-ingress.yaml
patches:
  - target:
      kind: Ingress
      name: argocd-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: argocd.platform.intelerad.com
